name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Ajout de la variable d'environnement globale pour forcer Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Mise à jour de la version 20 vers la 24
          
      - name: Install dependencies
        # Force l'installation de Tailwind CSS version 3 pour garantir la compatibilité avec notre configuration
        run: npm install && npm install lucide-react tailwindcss@^3.4.0 postcss autoprefixer @tailwindcss/typography
        
      - name: Build project
        # Création d'un fichier .env à la volée avant de compiler
        run: |
          echo "VITE_GEMINI_API_KEY=${{ secrets.VITE_GEMINI_API_KEY }}" > .env
          npm run build
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
